/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Clases.Conectar;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableRowSorter;
import javax.swing.text.Document;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
//.*;

/**
 *
 * @author Christian Delgado
 */
public class AdministracionIngles extends javax.swing.JFrame {

    private String campogrupo;
    private String campoespecialidad;
    private String camponControlIngles;
    /**
     * Creates new form AdministracionGrupos
     */
    int xMouse, yMouse;

    public AdministracionIngles(String grupo, String especialidad, String nControlIngles) {
        this.campogrupo = grupo;
        this.campoespecialidad = especialidad;
        this.camponControlIngles = nControlIngles;

        initComponents();
        this.setLocationRelativeTo(null);

        txtGrupo.setText(grupo);
        txtEspecialidad.setText(especialidad);
        txtnControlIngles.setText(nControlIngles);

        insertarAlumnos();
        cargarAlumnosEnTabla(grupo, nControlIngles);

        cerrar();
    }

    //Constructor
    private AdministracionIngles() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnosGrupoIngles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtnControlIngles = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        backTxt = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        minimizeBtn4 = new javax.swing.JPanel();
        minimizeTxt4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JLabel();
        btnCambiarCalificaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 642));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAlumnosGrupoIngles.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaAlumnosGrupoIngles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaAlumnosGrupoIngles.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tablaAlumnosGrupoIngles.setGridColor(new java.awt.Color(0, 0, 0));
        tablaAlumnosGrupoIngles.setOpaque(false);
        tablaAlumnosGrupoIngles.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tablaAlumnosGrupoIngles.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaAlumnosGrupoIngles.setShowVerticalLines(true);
        tablaAlumnosGrupoIngles.getTableHeader().setResizingAllowed(false);
        tablaAlumnosGrupoIngles.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaAlumnosGrupoIngles);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, 770, 500));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setText("Grupo Inglés:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        txtnControlIngles.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtnControlIngles.setText("jLabel4");
        jPanel4.add(txtnControlIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 160, -1));

        txtGrupo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGrupo.setText("jLabel2");
        jPanel4.add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel4.setText("Grupo:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));

        backTxt.setBackground(new java.awt.Color(255, 255, 255));
        backTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backbtn.png"))); // NOI18N
        backTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        backTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addComponent(backTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        minimizeBtn4.setBackground(new java.awt.Color(255, 255, 255));
        minimizeBtn4.setPreferredSize(new java.awt.Dimension(40, 30));

        minimizeTxt4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        minimizeTxt4.setForeground(new java.awt.Color(0, 0, 0));
        minimizeTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeTxt4.setText("—");
        minimizeTxt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeTxt4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeTxt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeTxt4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizeBtn4Layout = new javax.swing.GroupLayout(minimizeBtn4);
        minimizeBtn4.setLayout(minimizeBtn4Layout);
        minimizeBtn4Layout.setHorizontalGroup(
            minimizeBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeBtn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizeTxt4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );
        minimizeBtn4Layout.setVerticalGroup(
            minimizeBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeBtn4Layout.createSequentialGroup()
                .addComponent(minimizeTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(minimizeBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel2.setText("Especialidad:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        txtEspecialidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEspecialidad.setText("jLabel4");
        jPanel4.add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));

        btnCambiarCalificaciones.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCambiarCalificaciones.setText("Cambiar calificaciones");
        btnCambiarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCalificacionesActionPerformed(evt);
            }
        });
        jPanel4.add(btnCambiarCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class CalificacionesTableModel extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {
            // Permitir editar las celdas de las columnas de calificaciones
            return column >= 2 && column <= 6;
        }

        @Override
        public void setValueAt(Object aValue, int row, int column) {
            super.setValueAt(aValue, row, column);

            if (column >= 2 && column <= 6) {
                // Calcular el promedio y actualizar la columna "Promedio"
                calcularPromedio(row);
                // Actualizar el valor en la base de datos
                actualizarCalificacionEnDB(row, column);
            }
        }

        private void calcularPromedio(int row) {
            float sumatoria = 0;
            int cantidadCalificaciones = 0;

            for (int i = 2; i <= 6; i++) {
                Object calificacion = getValueAt(row, i);
                if (calificacion != null) {
                    sumatoria += Float.parseFloat(calificacion.toString());
                    cantidadCalificaciones++;
                }
            }

            float promedio = sumatoria / cantidadCalificaciones;

            setValueAt(promedio, row, 7);
        }

        private void actualizarCalificacionEnDB(int row, int column) {
            // Aquí colocar el código para actualizar la calificación en la base de datos
            // Puedes obtener el nControl y el grupo desde las etiquetas txtGrupo y txtnControlIngles
            String nControl = txtGrupo.getText();
            String grupo = txtnControlIngles.getText();

            // Obtener el nombre de la columna (speaking, reading, listening, writing, use_of_english)
            String columnName = getColumnName(column);

            // Obtener el valor de la calificación
            Object calificacion = getValueAt(row, column);
        }
    }

    void cargarAlumnosEnTabla(String grupo, String nControlIngles) {
        grupo = txtGrupo.getText();
        nControlIngles = txtnControlIngles.getText();

        // Creamos una instancia del TableModel personalizado
        CalificacionesTableModel modelo = new CalificacionesTableModel();
        modelo.addColumn("nControl");
        modelo.addColumn("Nombre");
        modelo.addColumn("Speaking");
        modelo.addColumn("Reading");
        modelo.addColumn("Listening");
        modelo.addColumn("Writing");
        modelo.addColumn("UseOfEnglish");
        modelo.addColumn("Promedio");

        tablaAlumnosGrupoIngles.setModel(modelo);

        String sql = "SELECT ci.ncontrol, a.nombre, ci.speaking, ci.reading, ci.listening, ci.writing, ci.use_of_english, ci.promedioIngles "
                + "FROM calificaciones_ingles ci "
                + "INNER JOIN alumnos a ON ci.ncontrol = a.ncontrol "
                + "WHERE ci.grupo = ? AND ci.ncontrolasignatura = ?";

        try {
            PreparedStatement statement = cn.prepareStatement(sql);
            statement.setString(1, grupo);
            statement.setString(2, nControlIngles);
            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                String nControl = rs.getString("ncontrol");
                String nombre = rs.getString("nombre");
                Float speaking = rs.getFloat("speaking");
                Float reading = rs.getFloat("reading");
                Float listening = rs.getFloat("listening");
                Float writing = rs.getFloat("writing");
                Float use_of_english = rs.getFloat("use_of_english");
                Float promedioIngles = rs.getFloat("promedioIngles");

                modelo.addRow(new Object[]{nControl, nombre, speaking, reading, listening, writing, use_of_english, promedioIngles});
            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al cargar datos de alumnos, contacte al administrador");
        }

        // Ajustar automáticamente el tamaño de las columnas según el contenido
        tablaAlumnosGrupoIngles.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(1).setPreferredWidth(250); // Ajustar el ancho de la columna "nombre"
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(2).setPreferredWidth(80);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(5).setPreferredWidth(80);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(6).setPreferredWidth(100);
        tablaAlumnosGrupoIngles.getColumnModel().getColumn(7).setPreferredWidth(100);
    }

    private void insertarAlumnos() {
        // Obtener el grupo y el nControl de inglés de los labels
        String grupo = txtGrupo.getText();
        String nControlIngles = txtnControlIngles.getText();

        // Realizar una consulta en la tabla calificaciones para obtener los alumnos que coinciden con el grupo y el nControl de inglés
        List<String> nControlAlumnos = new ArrayList<>();
        String sql = "SELECT DISTINCT ncontrol FROM dbo.calificaciones WHERE grupo = ? AND nControlAsignatura = ?";
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, grupo);
            pst.setString(2, nControlIngles);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String nControl = rs.getString("ncontrol");
                nControlAlumnos.add(nControl);
            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al obtener los nControl de los alumnos. Contacta al administrador.");
            return;
        }

        // Insertar los registros en la tabla calificaciones_ingles si no existen
        int registrosInsertados = 0;
        String insertSql = "INSERT INTO dbo.calificaciones_ingles (ncontrol, grupo, ncontrolasignatura, speaking, reading, listening, writing, use_of_english, promedioIngles) VALUES (?, ?, ?, NULL, NULL, NULL, NULL, NULL, NULL)";
        try {
            PreparedStatement insertPst = cn.prepareStatement(insertSql);

            for (String nControl : nControlAlumnos) {
                // Verificar si el registro ya existe en la tabla calificaciones_ingles
                boolean registroExistente = verificarRegistroExistenteEnCalificacionesIngles(grupo, nControlIngles, nControl);

                if (!registroExistente) {
                    insertPst.setString(1, nControl);
                    insertPst.setString(2, grupo);
                    insertPst.setString(3, nControlIngles);

                    int resultado = insertPst.executeUpdate();
                    if (resultado > 0) {
                        registrosInsertados++;
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al insertar el registro en la tabla calificaciones_ingles. Contacta al administrador.");
                    }
                }
            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al insertar el registro en la tabla calificaciones_ingles. Contacta al administrador.");
        }

        if (registrosInsertados > 0) {
            JOptionPane.showMessageDialog(null, "Se han insertado " + registrosInsertados + " registros en la tabla calificaciones_ingles exitosamente.");
        }

        // Actualizar la tabla de calificaciones_ingles con los registros insertados
        cargarAlumnosEnTabla(grupo, nControlIngles);
    }

    private boolean verificarRegistroExistenteEnCalificacionesIngles(String grupo, String nControlIngles, String nControlAlumno) {
        String sql = "SELECT COUNT(*) FROM dbo.calificaciones_ingles "
                + "WHERE grupo = ? AND ncontrolasignatura = ? AND ncontrol = ?";
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, grupo);
            pst.setString(2, nControlIngles);
            pst.setString(3, nControlAlumno);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int count = rs.getInt(1);
                return count > 0;
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        return false;
    }

    private void backTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseClicked
        AdministracionGrupos adminGrupos = new AdministracionGrupos(campogrupo, campoespecialidad);
        adminGrupos.setVisible(true);
        dispose();
    }//GEN-LAST:event_backTxtMouseClicked

    private void backTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseEntered
        backBtn.setBackground(Color.CYAN);
        backBtn.setForeground(Color.white);
    }//GEN-LAST:event_backTxtMouseEntered

    private void backTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseExited
        backBtn.setBackground(Color.white);
        backBtn.setForeground(Color.black);
    }//GEN-LAST:event_backTxtMouseExited

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro de cerrar el sistema?", "Confirmar salida", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void minimizeTxt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeTxt4MouseClicked
        setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeTxt4MouseClicked

    private void minimizeTxt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeTxt4MouseEntered
        minimizeBtn4.setBackground(Color.GRAY);
        minimizeTxt4.setForeground(Color.white);
    }//GEN-LAST:event_minimizeTxt4MouseEntered

    private void minimizeTxt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeTxt4MouseExited
        minimizeBtn4.setBackground(Color.white);
        minimizeTxt4.setForeground(Color.black);
    }//GEN-LAST:event_minimizeTxt4MouseExited


    private void btnCambiarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCalificacionesActionPerformed
        String sql = "UPDATE calificaciones_ingles "
                + "SET speaking = ?, reading = ?, listening = ?, writing = ?, use_of_english = ?, promedioIngles = ? "
                + "WHERE ncontrol = ? AND grupo = ? AND ncontrolasignatura = ?";

        try {
            PreparedStatement pst = cn.prepareStatement(sql);

            for (int row = 0; row < tablaAlumnosGrupoIngles.getRowCount(); row++) {
                String nControl = tablaAlumnosGrupoIngles.getValueAt(row, 0).toString();
                Float speaking = Float.parseFloat(tablaAlumnosGrupoIngles.getValueAt(row, 2).toString());
                Float reading = Float.parseFloat(tablaAlumnosGrupoIngles.getValueAt(row, 3).toString());
                Float listening = Float.parseFloat(tablaAlumnosGrupoIngles.getValueAt(row, 4).toString());
                Float writing = Float.parseFloat(tablaAlumnosGrupoIngles.getValueAt(row, 5).toString());
                Float useOfEnglish = Float.parseFloat(tablaAlumnosGrupoIngles.getValueAt(row, 6).toString());
                Float promedioIngles = (speaking + reading + listening + writing + useOfEnglish) / 5;
                promedioIngles = redondear(promedioIngles, 2); // Redondear el promedio a 2 decimales

                pst.setFloat(1, speaking);
                pst.setFloat(2, reading);
                pst.setFloat(3, listening);
                pst.setFloat(4, writing);
                pst.setFloat(5, useOfEnglish);
                pst.setFloat(6, promedioIngles);
                pst.setString(7, nControl);
                pst.setString(8, txtGrupo.getText());
                pst.setString(9, txtnControlIngles.getText());

                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(null, "Calificaciones guardadas exitosamente.");
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al guardar calificaciones. Contacte al administrador.");
        }
    }

    private float redondear(float valor, int decimales) {
        float factor = (float) Math.pow(10, decimales);
        return Math.round(valor * factor) / factor;
    }//GEN-LAST:event_btnCambiarCalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionIngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionIngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionIngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionIngles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionIngles().setVisible(true);
            }
        });
    }

    public void cerrarConexion(Connection conn) {
        if (conn != null) {
            try {
                // Cerrar la conexión
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public void cerrar() {

        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {

                public void windowClosing(WindowEvent e) {

                    confirmarSalida();

                }

            });

        } catch (Exception e) {
        }
    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Deseas cerrar la aplicacion?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (valor == JOptionPane.YES_OPTION) {

            JOptionPane.showMessageDialog(null, "Hasta pronto", "", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);

        }

    }

    Conectar con = new Conectar();
    Connection cn = con.conexion();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel backTxt;
    private javax.swing.JButton btnCambiarCalificaciones;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel minimizeBtn4;
    private javax.swing.JLabel minimizeTxt4;
    private javax.swing.JTable tablaAlumnosGrupoIngles;
    private javax.swing.JLabel txtEspecialidad;
    private javax.swing.JLabel txtGrupo;
    private javax.swing.JLabel txtnControlIngles;
    // End of variables declaration//GEN-END:variables
}
